ALTER TABLE `outbox_event`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN `event_type` VARCHAR(128) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN `payload_json` JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '发布状态',
    MODIFY COLUMN `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN `next_retry_time` DATETIME(3) NULL DEFAULT NULL COMMENT '下次重试时间',
    MODIFY COLUMN `lease_token` VARCHAR(36) NULL DEFAULT NULL COMMENT '发布租约令牌',
    MODIFY COLUMN `lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN `last_error` VARCHAR(1000) NULL DEFAULT NULL COMMENT '最近一次发布失败原因',
    MODIFY COLUMN `failed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '最终发布失败时间',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '事件创建时间',
    MODIFY COLUMN `published_at` DATETIME(3) NULL DEFAULT NULL COMMENT '发布成功时间';

ALTER TABLE `paper`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '试卷主键',
    MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '试卷名称',
    MODIFY COLUMN `subject_id` BIGINT NOT NULL COMMENT '学科 ID',
    MODIFY COLUMN `description` VARCHAR(255) NULL DEFAULT NULL COMMENT '试卷说明',
    MODIFY COLUMN `total_score` INT NOT NULL DEFAULT 0 COMMENT '试卷总分',
    MODIFY COLUMN `teacher_id` BIGINT NULL DEFAULT NULL COMMENT '创建教师 ID',
    MODIFY COLUMN `version` BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `paper_question`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '试卷题目关联主键',
    MODIFY COLUMN `paper_id` BIGINT NOT NULL COMMENT '试卷 ID',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '题目 ID',
    MODIFY COLUMN `score` INT NOT NULL COMMENT '本题分值',
    MODIFY COLUMN `sort_order` INT NOT NULL COMMENT '题目排序号',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `paper_snapshot`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '试卷快照主键',
    MODIFY COLUMN `paper_id` BIGINT NOT NULL COMMENT '来源试卷 ID',
    MODIFY COLUMN `version` BIGINT NOT NULL COMMENT '快照版本号',
    MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '快照试卷名称',
    MODIFY COLUMN `subject_id` BIGINT NOT NULL COMMENT '学科 ID',
    MODIFY COLUMN `total_score` INT NOT NULL COMMENT '快照总分',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '快照创建时间';

ALTER TABLE `paper_snapshot_asset`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '快照题目资源主键',
    MODIFY COLUMN `snapshot_id` BIGINT NOT NULL COMMENT '试卷快照 ID',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '题目 ID',
    MODIFY COLUMN `source_asset_id` BIGINT NOT NULL COMMENT '来源题目资源 ID',
    MODIFY COLUMN `file_type` VARCHAR(16) NOT NULL COMMENT '文件类型',
    MODIFY COLUMN `url` VARCHAR(512) NOT NULL COMMENT '资源访问地址',
    MODIFY COLUMN `object_key` VARCHAR(255) NOT NULL COMMENT '对象存储键',
    MODIFY COLUMN `original_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '原始文件名',
    MODIFY COLUMN `content_type` VARCHAR(128) NULL DEFAULT NULL COMMENT '媒体类型',
    MODIFY COLUMN `size` BIGINT NULL DEFAULT NULL COMMENT '文件大小（字节）';

ALTER TABLE `paper_snapshot_question`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '快照题目主键',
    MODIFY COLUMN `snapshot_id` BIGINT NOT NULL COMMENT '试卷快照 ID',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '来源题目 ID',
    MODIFY COLUMN `type` VARCHAR(16) NOT NULL COMMENT '题目类型',
    MODIFY COLUMN `difficulty` VARCHAR(16) NOT NULL COMMENT '题目难度',
    MODIFY COLUMN `content` TEXT NOT NULL COMMENT '题目内容',
    MODIFY COLUMN `options_json` TEXT NULL COMMENT '选项 JSON',
    MODIFY COLUMN `answer` TEXT NOT NULL COMMENT '标准答案',
    MODIFY COLUMN `analysis` TEXT NULL COMMENT '题目解析',
    MODIFY COLUMN `score` INT NOT NULL COMMENT '本题分值',
    MODIFY COLUMN `sort_order` INT NOT NULL COMMENT '题目排序号';

ALTER TABLE `question`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '题目主键',
    MODIFY COLUMN `subject_id` BIGINT NOT NULL COMMENT '学科 ID',
    MODIFY COLUMN `type` VARCHAR(16) NOT NULL COMMENT '题目类型',
    MODIFY COLUMN `difficulty` VARCHAR(16) NOT NULL COMMENT '题目难度',
    MODIFY COLUMN `content` TEXT NOT NULL COMMENT '题目内容',
    MODIFY COLUMN `options_json` TEXT NULL COMMENT '选项 JSON',
    MODIFY COLUMN `answer` TEXT NOT NULL COMMENT '标准答案',
    MODIFY COLUMN `analysis` TEXT NULL COMMENT '题目解析',
    MODIFY COLUMN `default_score` INT NOT NULL DEFAULT 0 COMMENT '默认分值',
    MODIFY COLUMN `creator_id` BIGINT NULL DEFAULT NULL COMMENT '出题人 ID',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `question_asset`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '题目资源主键',
    MODIFY COLUMN `question_id` BIGINT NULL DEFAULT NULL COMMENT '题目 ID',
    MODIFY COLUMN `uploader_id` BIGINT NOT NULL COMMENT '上传人 ID',
    MODIFY COLUMN `file_type` VARCHAR(16) NOT NULL COMMENT '文件类型',
    MODIFY COLUMN `url` VARCHAR(512) NOT NULL COMMENT '资源访问地址',
    MODIFY COLUMN `object_key` VARCHAR(255) NOT NULL COMMENT '对象存储键',
    MODIFY COLUMN `original_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '原始文件名',
    MODIFY COLUMN `content_type` VARCHAR(128) NULL DEFAULT NULL COMMENT '媒体类型',
    MODIFY COLUMN `size` BIGINT NULL DEFAULT NULL COMMENT '文件大小（字节）',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';
