ALTER TABLE `outbox_event`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN `event_type` VARCHAR(128) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN `payload_json` JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '发布状态',
    MODIFY COLUMN `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN `next_retry_time` DATETIME(3) NULL DEFAULT NULL COMMENT '下次重试时间',
    MODIFY COLUMN `lease_token` VARCHAR(36) NULL DEFAULT NULL COMMENT '发布租约令牌',
    MODIFY COLUMN `lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN `last_error` VARCHAR(1000) NULL DEFAULT NULL COMMENT '最近一次发布失败原因',
    MODIFY COLUMN `failed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '最终发布失败时间',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '事件创建时间',
    MODIFY COLUMN `published_at` DATETIME(3) NULL DEFAULT NULL COMMENT '发布成功时间';

ALTER TABLE `sys_role`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '角色主键',
    MODIFY COLUMN `code` VARCHAR(32) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `sys_user`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '用户主键',
    MODIFY COLUMN `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
    MODIFY COLUMN `password` VARCHAR(255) NOT NULL COMMENT '密码哈希',
    MODIFY COLUMN `real_name` VARCHAR(64) NOT NULL COMMENT '真实姓名',
    MODIFY COLUMN `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用（1是，0否）',
    MODIFY COLUMN `token_version` BIGINT NOT NULL DEFAULT 0 COMMENT '令牌版本号',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `sys_user_role`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '用户角色关联主键',
    MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN `role_id` BIGINT NOT NULL COMMENT '角色 ID',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';
