ALTER TABLE `anti_cheat_event`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '防作弊事件主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `event_type` VARCHAR(64) NOT NULL COMMENT '作弊事件类型',
    MODIFY COLUMN `event_time` DATETIME(3) NOT NULL COMMENT '事件发生时间',
    MODIFY COLUMN `duration_ms` BIGINT NULL DEFAULT NULL COMMENT '事件持续时长（毫秒）',
    MODIFY COLUMN `payload` TEXT NULL COMMENT '事件载荷',
    MODIFY COLUMN `evidence_json` TEXT NULL COMMENT '取证信息 JSON',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `exam_session`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '考试会话主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '考试会话状态',
    MODIFY COLUMN `start_time` DATETIME(3) NULL DEFAULT NULL COMMENT '考试开始时间',
    MODIFY COLUMN `deadline_time` DATETIME(3) NULL DEFAULT NULL COMMENT '作答截止时间',
    MODIFY COLUMN `end_time` DATETIME(3) NULL DEFAULT NULL COMMENT '考试结束时间',
    MODIFY COLUMN `last_snapshot_time` DATETIME(3) NULL DEFAULT NULL COMMENT '最后一次答题快照时间',
    MODIFY COLUMN `claim_time` DATETIME(3) NULL DEFAULT NULL COMMENT '超时交卷抢占时间',
    MODIFY COLUMN `active_client_id` VARCHAR(128) NULL DEFAULT NULL COMMENT '当前活跃客户端标识',
    MODIFY COLUMN `active_client_token` VARCHAR(128) NULL DEFAULT NULL COMMENT '当前客户端租约令牌',
    MODIFY COLUMN `active_client_lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '客户端租约到期时间',
    MODIFY COLUMN `active_client_last_seen` DATETIME(3) NULL DEFAULT NULL COMMENT '客户端最后心跳时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `outbox_event`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN `event_type` VARCHAR(128) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN `payload_json` JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '发布状态',
    MODIFY COLUMN `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN `next_retry_time` DATETIME(3) NULL DEFAULT NULL COMMENT '下次重试时间',
    MODIFY COLUMN `lease_token` VARCHAR(36) NULL DEFAULT NULL COMMENT '发布租约令牌',
    MODIFY COLUMN `lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN `last_error` VARCHAR(1000) NULL DEFAULT NULL COMMENT '最近一次发布失败原因',
    MODIFY COLUMN `failed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '最终发布失败时间',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '事件创建时间',
    MODIFY COLUMN `published_at` DATETIME(3) NULL DEFAULT NULL COMMENT '发布成功时间';

ALTER TABLE `proctoring_disposition`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '监考处置记录主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '处置状态',
    MODIFY COLUMN `remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '处置备注',
    MODIFY COLUMN `handled_by` BIGINT NULL DEFAULT NULL COMMENT '处置人 ID',
    MODIFY COLUMN `handled_at` DATETIME(3) NULL DEFAULT NULL COMMENT '处置时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `submission`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '考试提交主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '提交状态',
    MODIFY COLUMN `paper_snapshot_id` BIGINT NULL DEFAULT NULL COMMENT '试卷快照 ID',
    MODIFY COLUMN `submitted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '提交时间',
    MODIFY COLUMN `timeout_submit` TINYINT NOT NULL DEFAULT 0 COMMENT '是否超时自动提交（1是，0否）',
    MODIFY COLUMN `draft_version` BIGINT NOT NULL DEFAULT 0 COMMENT '答题草稿版本号',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `submission_answer`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '提交答案主键',
    MODIFY COLUMN `submission_id` BIGINT NOT NULL COMMENT '考试提交 ID',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '题目 ID',
    MODIFY COLUMN `answer_text` TEXT NULL COMMENT '作答内容',
    MODIFY COLUMN `final_answer` TINYINT NULL DEFAULT NULL COMMENT '是否最终答案（1是，0否）',
    MODIFY COLUMN `source` VARCHAR(32) NULL DEFAULT NULL COMMENT '答案来源',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';
