ALTER TABLE `inbox_event`
    MODIFY COLUMN `event_id` VARCHAR(36) NOT NULL COMMENT '消息事件标识',
    MODIFY COLUMN `consumer_name` VARCHAR(64) NOT NULL COMMENT '消费者名称',
    MODIFY COLUMN `processed_at` DATETIME(3) NOT NULL COMMENT '消息处理完成时间';

ALTER TABLE `operation_audit_log`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '操作审计日志主键',
    MODIFY COLUMN `operator_id` BIGINT NULL DEFAULT NULL COMMENT '操作人 ID',
    MODIFY COLUMN `operator_username` VARCHAR(128) NULL DEFAULT NULL COMMENT '操作人用户名',
    MODIFY COLUMN `operator_roles` VARCHAR(255) NULL DEFAULT NULL COMMENT '操作人角色集合',
    MODIFY COLUMN `action` VARCHAR(64) NOT NULL COMMENT '操作动作',
    MODIFY COLUMN `target_type` VARCHAR(64) NOT NULL COMMENT '操作对象类型',
    MODIFY COLUMN `target_id` VARCHAR(128) NULL DEFAULT NULL COMMENT '操作对象标识',
    MODIFY COLUMN `request_method` VARCHAR(16) NULL DEFAULT NULL COMMENT '请求方法',
    MODIFY COLUMN `request_path` VARCHAR(255) NULL DEFAULT NULL COMMENT '请求路径',
    MODIFY COLUMN `request_ip` VARCHAR(64) NULL DEFAULT NULL COMMENT '请求来源 IP',
    MODIFY COLUMN `detail` TEXT NULL COMMENT '操作详情',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL COMMENT '执行状态',
    MODIFY COLUMN `error_message` VARCHAR(500) NULL DEFAULT NULL COMMENT '失败原因',
    MODIFY COLUMN `operate_time` DATETIME(3) NOT NULL COMMENT '操作发生时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `rpt_exam`
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '考试名称',
    MODIFY COLUMN `subject_id` BIGINT NULL DEFAULT NULL COMMENT '学科 ID',
    MODIFY COLUMN `subject_name` VARCHAR(128) NULL DEFAULT NULL COMMENT '学科名称',
    MODIFY COLUMN `start_time` DATETIME(3) NOT NULL COMMENT '考试开始时间',
    MODIFY COLUMN `end_time` DATETIME(3) NOT NULL COMMENT '考试结束时间',
    MODIFY COLUMN `duration_minutes` INT NOT NULL COMMENT '考试时长（分钟）',
    MODIFY COLUMN `pass_score` INT NOT NULL COMMENT '及格分数',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '考试状态',
    MODIFY COLUMN `publisher_id` BIGINT NULL DEFAULT NULL COMMENT '发布人 ID',
    MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '投影更新时间';

ALTER TABLE `rpt_exam_candidate`
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `class_id` BIGINT NULL DEFAULT NULL COMMENT '教学班 ID',
    MODIFY COLUMN `class_name` VARCHAR(128) NULL DEFAULT NULL COMMENT '教学班名称',
    MODIFY COLUMN `student_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '学号',
    MODIFY COLUMN `username` VARCHAR(64) NULL DEFAULT NULL COMMENT '用户名',
    MODIFY COLUMN `student_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '学生姓名',
    MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '投影更新时间';

ALTER TABLE `rpt_objective_answer`
    MODIFY COLUMN `submission_id` BIGINT NOT NULL COMMENT '提交记录 ID',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '题目 ID',
    MODIFY COLUMN `question_content` TEXT NULL COMMENT '题目内容快照',
    MODIFY COLUMN `correct_flag` TINYINT NOT NULL COMMENT '是否答对（1是，0否）',
    MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '投影更新时间';

ALTER TABLE `rpt_proctoring_student`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '监考学生投影主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `student_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '学生姓名',
    MODIFY COLUMN `class_names_json` JSON NULL COMMENT '教学班名称 JSON',
    MODIFY COLUMN `session_status` VARCHAR(32) NULL DEFAULT NULL COMMENT '考试会话状态',
    MODIFY COLUMN `submission_status` VARCHAR(32) NULL DEFAULT NULL COMMENT '提交状态',
    MODIFY COLUMN `event_count` INT NOT NULL DEFAULT 0 COMMENT '防作弊事件数量',
    MODIFY COLUMN `last_event_time` DATETIME(3) NULL DEFAULT NULL COMMENT '最近防作弊事件时间',
    MODIFY COLUMN `latest_event_type` VARCHAR(64) NULL DEFAULT NULL COMMENT '最近防作弊事件类型',
    MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '投影更新时间';

ALTER TABLE `rpt_student_score`
    MODIFY COLUMN `submission_id` BIGINT NOT NULL COMMENT '提交记录 ID',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `student_name` VARCHAR(64) NULL DEFAULT NULL COMMENT '学生姓名',
    MODIFY COLUMN `class_names_json` JSON NULL COMMENT '教学班名称 JSON',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '阅卷状态',
    MODIFY COLUMN `objective_score` INT NULL DEFAULT NULL COMMENT '客观题得分',
    MODIFY COLUMN `subjective_score` INT NULL DEFAULT NULL COMMENT '主观题得分',
    MODIFY COLUMN `total_score` INT NULL DEFAULT NULL COMMENT '总分',
    MODIFY COLUMN `pass_flag` TINYINT NULL DEFAULT NULL COMMENT '是否及格（1是，0否）',
    MODIFY COLUMN `submitted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '交卷时间',
    MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL COMMENT '投影更新时间';
