spring:
  application: { name: exam-runtime-service }
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery: { namespace: "${NACOS_NAMESPACE:dev}", group: EXAM_GROUP }
      config: { namespace: "${NACOS_NAMESPACE:dev}", group: EXAM_GROUP }
  config:
    import: ["optional:nacos:exam-common.yml?group=EXAM_GROUP&refreshEnabled=true", "optional:nacos:exam-runtime-service.yml?group=EXAM_GROUP&refreshEnabled=true"]
server: { port: "${SERVER_PORT:16735}" }
xxl:
  job:
    admin-addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://127.0.0.1:8080/xxl-job-admin}
    access-token: ${XXL_JOB_ACCESS_TOKEN:}
    executor:
      appname: exam-runtime-executor
      address: ${XXL_JOB_EXECUTOR_ADDRESS:}
      ip: ${XXL_JOB_EXECUTOR_IP:}
      port: ${XXL_JOB_EXECUTOR_PORT:19999}
      log-path: ${XXL_JOB_LOG_PATH:./logs/xxl-job}
      log-retention-days: 30
