ALTER TABLE `exam`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '考试主键',
    MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '考试名称',
    MODIFY COLUMN `paper_id` BIGINT NOT NULL COMMENT '来源试卷 ID',
    MODIFY COLUMN `start_time` DATETIME(3) NOT NULL COMMENT '考试开始时间',
    MODIFY COLUMN `end_time` DATETIME(3) NOT NULL COMMENT '考试结束时间',
    MODIFY COLUMN `duration_minutes` INT NOT NULL COMMENT '考试时长（分钟）',
    MODIFY COLUMN `pass_score` INT NOT NULL COMMENT '及格分数',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL COMMENT '考试状态',
    MODIFY COLUMN `publisher_id` BIGINT NULL DEFAULT NULL COMMENT '发布人 ID',
    MODIFY COLUMN `proctoring_level` VARCHAR(32) NOT NULL DEFAULT 'STANDARD' COMMENT '监考等级',
    MODIFY COLUMN `proctoring_config_json` TEXT NULL COMMENT '监考配置 JSON',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `exam_candidate`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '考试考生关联主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `class_id` BIGINT NOT NULL COMMENT '教学班 ID',
    MODIFY COLUMN `roster_version` BIGINT NOT NULL COMMENT '花名册版本号',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '考生名单生成时间';

ALTER TABLE `exam_paper_ref`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '考试试卷快照关联主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `paper_snapshot_id` BIGINT NOT NULL COMMENT '试卷快照 ID',
    MODIFY COLUMN `snapshot_version` BIGINT NOT NULL COMMENT '试卷快照版本号',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '关联创建时间';

ALTER TABLE `exam_target_class`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '考试目标教学班关联主键',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `class_id` BIGINT NOT NULL COMMENT '教学班 ID',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `outbox_event`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN `event_type` VARCHAR(128) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN `payload_json` JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '发布状态',
    MODIFY COLUMN `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN `next_retry_time` DATETIME(3) NULL DEFAULT NULL COMMENT '下次重试时间',
    MODIFY COLUMN `lease_token` VARCHAR(36) NULL DEFAULT NULL COMMENT '发布租约令牌',
    MODIFY COLUMN `lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN `last_error` VARCHAR(1000) NULL DEFAULT NULL COMMENT '最近一次发布失败原因',
    MODIFY COLUMN `failed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '最终发布失败时间',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '事件创建时间',
    MODIFY COLUMN `published_at` DATETIME(3) NULL DEFAULT NULL COMMENT '发布成功时间';
