START TRANSACTION;

-- 计算机网络：5 单选、5 多选、4 判断、2 填空、4 简答。
INSERT INTO question(id, subject_id, type, difficulty, content, options_json, answer, analysis, default_score, creator_id, create_time, update_time, create_by, update_by) VALUES
  (10001001, 10001, 'SINGLE', 'EASY', 'OSI 参考模型中，负责逻辑寻址和路由选择的是哪一层？', '[{"label":"A","value":"物理层"},{"label":"B","value":"网络层"},{"label":"C","value":"传输层"},{"label":"D","value":"表示层"}]', 'B', '网络层使用逻辑地址并负责跨网络的路径选择与分组转发。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001002, 10001, 'SINGLE', 'EASY', 'DNS 服务默认使用的端口号是？', '[{"label":"A","value":"21"},{"label":"B","value":"25"},{"label":"C","value":"53"},{"label":"D","value":"110"}]', 'C', 'DNS 通常在 UDP 或 TCP 的 53 端口提供服务。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001003, 10001, 'SINGLE', 'EASY', '下列哪种传输层协议提供面向连接的可靠字节流？', '[{"label":"A","value":"UDP"},{"label":"B","value":"TCP"},{"label":"C","value":"IP"},{"label":"D","value":"ICMP"}]', 'B', 'TCP 通过确认、重传、排序和流量控制提供可靠字节流。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001004, 10001, 'SINGLE', 'EASY', 'IPv4 地址的长度是多少位？', '[{"label":"A","value":"16 位"},{"label":"B","value":"24 位"},{"label":"C","value":"32 位"},{"label":"D","value":"128 位"}]', 'C', 'IPv4 地址长度为 32 位，IPv6 地址长度为 128 位。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001005, 10001, 'SINGLE', 'MEDIUM', '以太网交换机学习并转发帧时主要依据什么地址？', '[{"label":"A","value":"IP 地址"},{"label":"B","value":"MAC 地址"},{"label":"C","value":"端口号"},{"label":"D","value":"域名"}]', 'B', '二层交换机根据源 MAC 学习转发表，并依据目的 MAC 转发帧。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001006, 10001, 'MULTI', 'MEDIUM', '下列哪些属于 TCP 的特征？', '[{"label":"A","value":"面向连接"},{"label":"B","value":"可靠传输"},{"label":"C","value":"保留应用消息边界"},{"label":"D","value":"支持流量控制和拥塞控制"}]', 'A,B,D', 'TCP 面向连接、提供可靠字节流并实施流量与拥塞控制，但不保留消息边界。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001007, 10001, 'MULTI', 'EASY', '下列哪些是应用层协议？', '[{"label":"A","value":"HTTP"},{"label":"B","value":"DNS"},{"label":"C","value":"SMTP"},{"label":"D","value":"ARP"}]', 'A,B,C', 'HTTP、DNS 和 SMTP 属于应用层协议；ARP 用于地址解析。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001008, 10001, 'MULTI', 'MEDIUM', '下列哪些网段属于 RFC 1918 定义的私有 IPv4 地址空间？', '[{"label":"A","value":"10.0.0.0/8"},{"label":"B","value":"172.16.0.0/12"},{"label":"C","value":"192.168.0.0/16"},{"label":"D","value":"100.64.0.0/10"}]', 'A,B,C', 'RFC 1918 定义了前三个私有网段；100.64.0.0/10 是运营商级 NAT 共享地址空间。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001009, 10001, 'MULTI', 'MEDIUM', '路由器通常承担哪些功能？', '[{"label":"A","value":"路径选择"},{"label":"B","value":"分组转发"},{"label":"C","value":"隔离二层广播域"},{"label":"D","value":"强制加密所有业务流量"}]', 'A,B,C', '路由器负责选路和转发，并划分广播域；加密不是所有路由器的必然功能。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001010, 10001, 'MULTI', 'HARD', '按照 HTTP 语义，下列哪些方法通常具有幂等性？', '[{"label":"A","value":"GET"},{"label":"B","value":"PUT"},{"label":"C","value":"DELETE"},{"label":"D","value":"POST"}]', 'A,B,C', 'GET、PUT、DELETE 被定义为幂等方法；POST 通常不保证幂等。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001011, 10001, 'JUDGE', 'EASY', 'UDP 是无连接协议，发送数据前不需要建立传输层连接。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', 'UDP 不执行类似 TCP 三次握手的连接建立过程。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001012, 10001, 'JUDGE', 'EASY', '普通二层以太网交换机根据目的 IP 地址决定帧的转发端口。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '普通二层交换机依据目的 MAC 地址查找转发表。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001013, 10001, 'JUDGE', 'MEDIUM', '在传统 IPv4 子网中，一个 /24 网段通常可分配给主机的地址数量为 254。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', '/24 有 256 个地址，扣除网络地址和广播地址后通常剩 254 个。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001014, 10001, 'JUDGE', 'MEDIUM', '只要网站使用 HTTPS，就能保证该网站的业务内容一定可信。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', 'HTTPS 保护传输并验证证书身份，但不能保证网站业务内容本身可信。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001015, 10001, 'BLANK', 'EASY', 'IPv4 环回地址通常写作 ______。', NULL, '127.0.0.1', '127.0.0.1 指向本地主机的环回接口。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001016, 10001, 'BLANK', 'MEDIUM', 'IPv4 首部中每经过一个路由器通常会减 1、用于限制分组生存时间的字段是 ______。', NULL, 'TTL', 'TTL 归零后路由器丢弃分组，从而避免分组永久循环。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001017, 10001, 'SHORT', 'MEDIUM', '简述 TCP 建立连接为什么采用三次握手。', NULL, '三次握手用于确认双方的发送与接收能力、同步初始序列号，并避免历史失效连接请求直接建立连接。', '答案应说明双向可达性、序列号同步以及对旧连接请求的防护。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001018, 10001, 'SHORT', 'MEDIUM', '说明 TCP 流量控制与拥塞控制的区别。', NULL, '流量控制保护接收端，依据接收窗口限制发送速率；拥塞控制保护网络，依据拥塞状态调整拥塞窗口。', '关键区别是控制对象分别为接收端处理能力和网络承载能力。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001019, 10001, 'SHORT', 'HARD', '简述浏览器进行递归 DNS 查询并获得目标 IP 地址的典型过程。', NULL, '浏览器先查本地缓存，再请求递归解析器；解析器按需查询根、顶级域和权威 DNS，获得记录后缓存并返回客户端。', '应包含本地缓存、递归解析器、根服务器、顶级域服务器和权威服务器。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10001020, 10001, 'SHORT', 'HARD', '说明划分子网的两个主要作用。', NULL, '划分子网可更有效地分配地址并缩小广播域，也便于实施路由汇总、安全隔离和分层管理。', '答出地址利用与广播域控制，并合理补充管理或安全作用即可。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2)
ON DUPLICATE KEY UPDATE subject_id=VALUES(subject_id), type=VALUES(type), difficulty=VALUES(difficulty), content=VALUES(content), options_json=VALUES(options_json), answer=VALUES(answer), analysis=VALUES(analysis), default_score=VALUES(default_score), creator_id=VALUES(creator_id), update_time=CURRENT_TIMESTAMP(3), update_by=VALUES(update_by);

-- 数据结构与算法：5 单选、5 多选、4 判断、2 填空、4 简答。
INSERT INTO question(id, subject_id, type, difficulty, content, options_json, answer, analysis, default_score, creator_id, create_time, update_time, create_by, update_by) VALUES
  (10002001, 10002, 'SINGLE', 'EASY', '栈的基本访问原则是？', '[{"label":"A","value":"先进先出"},{"label":"B","value":"后进先出"},{"label":"C","value":"随机访问"},{"label":"D","value":"按关键字访问"}]', 'B', '栈只在栈顶进行插入和删除，因此遵循后进先出原则。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002002, 10002, 'SINGLE', 'EASY', '广度优先搜索通常使用哪种数据结构保存待访问结点？', '[{"label":"A","value":"栈"},{"label":"B","value":"队列"},{"label":"C","value":"散列表"},{"label":"D","value":"堆"}]', 'B', '队列保证结点按层次顺序被访问。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002003, 10002, 'SINGLE', 'EASY', '在有序数组上进行二分查找的时间复杂度是？', '[{"label":"A","value":"O(1)"},{"label":"B","value":"O(log n)"},{"label":"C","value":"O(n)"},{"label":"D","value":"O(n²)"}]', 'B', '每次比较将搜索区间缩小为原来的一半。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002004, 10002, 'SINGLE', 'MEDIUM', '下列排序算法中，通常能够保持相同关键字元素相对次序的是？', '[{"label":"A","value":"快速排序"},{"label":"B","value":"堆排序"},{"label":"C","value":"归并排序"},{"label":"D","value":"选择排序"}]', 'C', '标准归并过程可在相等时优先取左侧元素，从而保持稳定性。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002005, 10002, 'SINGLE', 'MEDIUM', '对一个有向无环图进行拓扑排序后得到的是？', '[{"label":"A","value":"唯一的最短路径"},{"label":"B","value":"满足所有边先后约束的顶点线性序列"},{"label":"C","value":"最小生成树"},{"label":"D","value":"所有强连通分量"}]', 'B', '对每条边 u→v，拓扑序中 u 必须出现在 v 之前。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002006, 10002, 'MULTI', 'EASY', '下列哪些属于线性数据结构？', '[{"label":"A","value":"数组"},{"label":"B","value":"链表"},{"label":"C","value":"栈"},{"label":"D","value":"队列"}]', 'A,B,C,D', '这些结构中的元素都可按一条逻辑序列组织。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002007, 10002, 'MULTI', 'MEDIUM', '下列哪些遍历属于深度优先思想？', '[{"label":"A","value":"先序遍历"},{"label":"B","value":"中序遍历"},{"label":"C","value":"后序遍历"},{"label":"D","value":"层序遍历"}]', 'A,B,C', '先序、中序和后序沿分支深入；层序遍历属于广度优先。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002008, 10002, 'MULTI', 'MEDIUM', '处理散列冲突的常用方法有哪些？', '[{"label":"A","value":"链地址法"},{"label":"B","value":"开放寻址法"},{"label":"C","value":"再散列法"},{"label":"D","value":"拓扑排序"}]', 'A,B,C', '链地址、开放寻址和再散列都可用于处理冲突，拓扑排序与散列表无关。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002009, 10002, 'MULTI', 'HARD', '下列哪些排序算法的平均时间复杂度为 O(n log n)？', '[{"label":"A","value":"快速排序"},{"label":"B","value":"归并排序"},{"label":"C","value":"堆排序"},{"label":"D","value":"冒泡排序"}]', 'A,B,C', '快速排序平均为 O(n log n)，归并和堆排序为 O(n log n)，冒泡排序平均为 O(n²)。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002010, 10002, 'MULTI', 'HARD', '下列哪些算法可用于求解图中的最短路径问题？', '[{"label":"A","value":"Dijkstra 算法"},{"label":"B","value":"Bellman-Ford 算法"},{"label":"C","value":"Floyd-Warshall 算法"},{"label":"D","value":"Kruskal 算法"}]', 'A,B,C', '前三者用于最短路径；Kruskal 用于最小生成树。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002011, 10002, 'JUDGE', 'EASY', 'AVL 树中任意结点左右子树高度差的绝对值不超过 1。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', '这是 AVL 平衡二叉搜索树的平衡条件。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002012, 10002, 'JUDGE', 'EASY', '单链表可以像数组一样在 O(1) 时间内访问任意下标元素。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '单链表访问第 k 个元素通常需要从头遍历，复杂度为 O(k)。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002013, 10002, 'JUDGE', 'MEDIUM', '在所有边权相等的无权图中，广度优先搜索可以得到源点到其他可达顶点的最短路径。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', 'BFS 按路径边数逐层扩展，首次到达即得到最少边数路径。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002014, 10002, 'JUDGE', 'HARD', '任何基于比较的通用排序算法都能在最坏情况下达到 O(n) 时间复杂度。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '比较排序在一般模型下有 Ω(n log n) 的最坏情况复杂度下界。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002015, 10002, 'BLANK', 'EASY', '队列遵循的访问原则通常简称为 ______。', NULL, 'FIFO', 'FIFO 表示 First In First Out，即先进先出。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002016, 10002, 'BLANK', 'MEDIUM', '使用从 0 开始的数组存储二叉堆时，下标为 i 的非根结点，其父结点下标为 ______。', NULL, 'floor((i-1)/2)', '零下标二叉堆中父结点位置可由 floor((i-1)/2) 计算。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002017, 10002, 'SHORT', 'MEDIUM', '说明递归调用与调用栈之间的关系。', NULL, '每次递归调用都会创建新的栈帧保存参数、局部变量和返回地址；到达终止条件后栈帧按后进先出的顺序退出。', '应指出栈帧的创建、保存内容、终止条件和逆序返回。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002018, 10002, 'SHORT', 'MEDIUM', '简述散列表获得接近 O(1) 平均查找性能需要满足的条件。', NULL, '需要合理的散列函数、受控的装载因子、有效的冲突处理方式，并在容量不足时及时扩容。', '答案应围绕散列均匀性、装载因子和冲突处理展开。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002019, 10002, 'SHORT', 'HARD', '说明快速排序一次分区操作的目标。', NULL, '选择枢轴后重排区间，使枢轴一侧元素不大于它、另一侧元素不小于它，并确定枢轴的最终位置或等价分界。', '不同分区实现细节可不同，但必须形成可递归处理的两个子区间。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10002020, 10002, 'SHORT', 'HARD', '为什么标准 Dijkstra 算法不能直接处理负权边？', NULL, 'Dijkstra 依赖已确定最短距离不会再降低的贪心性质；负权边可能在结点确定后产生更短路径，从而破坏该性质。', '应说明贪心确定性被负权边破坏，而不仅是给出不能使用的结论。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2)
ON DUPLICATE KEY UPDATE subject_id=VALUES(subject_id), type=VALUES(type), difficulty=VALUES(difficulty), content=VALUES(content), options_json=VALUES(options_json), answer=VALUES(answer), analysis=VALUES(analysis), default_score=VALUES(default_score), creator_id=VALUES(creator_id), update_time=CURRENT_TIMESTAMP(3), update_by=VALUES(update_by);

-- 操作系统：5 单选、5 多选、4 判断、2 填空、4 简答。
INSERT INTO question(id, subject_id, type, difficulty, content, options_json, answer, analysis, default_score, creator_id, create_time, update_time, create_by, update_by) VALUES
  (10003001, 10003, 'SINGLE', 'EASY', '分页式虚拟内存中，虚拟地址空间被划分为固定大小的什么单位？', '[{"label":"A","value":"页"},{"label":"B","value":"段"},{"label":"C","value":"柱面"},{"label":"D","value":"目录"}]', 'A', '分页系统将虚拟地址空间划分为页，将物理内存划分为页框。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003002, 10003, 'SINGLE', 'EASY', '操作系统中资源分配和独立调度的传统基本单位是？', '[{"label":"A","value":"文件"},{"label":"B","value":"进程"},{"label":"C","value":"中断"},{"label":"D","value":"页面"}]', 'B', '传统定义中进程是资源分配和独立运行的基本单位。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003003, 10003, 'SINGLE', 'MEDIUM', '下列哪一项不是产生死锁的四个必要条件？', '[{"label":"A","value":"互斥"},{"label":"B","value":"请求并保持"},{"label":"C","value":"可剥夺"},{"label":"D","value":"循环等待"}]', 'C', '死锁条件包含不可剥夺，而不是可剥夺。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003004, 10003, 'SINGLE', 'MEDIUM', '最先进入内存的页面最先被淘汰，对应哪种页面置换算法？', '[{"label":"A","value":"FIFO"},{"label":"B","value":"LRU"},{"label":"C","value":"LFU"},{"label":"D","value":"CLOCK-Pro"}]', 'A', 'FIFO 按页面装入内存的先后顺序选择淘汰页面。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003005, 10003, 'SINGLE', 'MEDIUM', '用户程序请求操作系统内核服务的标准入口通常是？', '[{"label":"A","value":"系统调用"},{"label":"B","value":"宏替换"},{"label":"C","value":"动态链接"},{"label":"D","value":"轮询变量"}]', 'A', '系统调用触发受控的用户态到内核态切换。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003006, 10003, 'MULTI', 'EASY', '进程的经典基本状态包括哪些？', '[{"label":"A","value":"就绪"},{"label":"B","value":"运行"},{"label":"C","value":"阻塞"},{"label":"D","value":"编译"}]', 'A,B,C', '经典三状态模型包括就绪、运行和阻塞。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003007, 10003, 'MULTI', 'EASY', '下列哪些属于 CPU 调度算法？', '[{"label":"A","value":"先来先服务"},{"label":"B","value":"时间片轮转"},{"label":"C","value":"优先级调度"},{"label":"D","value":"两阶段提交"}]', 'A,B,C', '前三项用于处理器调度；两阶段提交属于分布式事务协议。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003008, 10003, 'MULTI', 'MEDIUM', '产生死锁的必要条件包括哪些？', '[{"label":"A","value":"互斥"},{"label":"B","value":"请求并保持"},{"label":"C","value":"不可剥夺"},{"label":"D","value":"循环等待"}]', 'A,B,C,D', '四个条件同时成立时系统才可能发生死锁。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003009, 10003, 'MULTI', 'MEDIUM', '常见的进程间通信方式有哪些？', '[{"label":"A","value":"管道"},{"label":"B","value":"共享内存"},{"label":"C","value":"消息队列"},{"label":"D","value":"页表遍历"}]', 'A,B,C', '管道、共享内存和消息队列都是 IPC 机制。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003010, 10003, 'MULTI', 'HARD', '文件系统通常需要维护哪些信息？', '[{"label":"A","value":"文件元数据"},{"label":"B","value":"目录层次关系"},{"label":"C","value":"磁盘块分配状态"},{"label":"D","value":"CPU 指令流水线状态"}]', 'A,B,C', '文件系统管理文件元数据、名称空间和存储块，CPU 流水线不属于其职责。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003011, 10003, 'JUDGE', 'EASY', '同一进程中的线程通常共享该进程的虚拟地址空间。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', '线程通常共享代码、堆和打开文件等进程资源，但各自拥有栈和寄存器上下文。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003012, 10003, 'JUDGE', 'MEDIUM', '信号量只能用于互斥，不能用于线程或进程之间的同步。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '信号量既可以实现互斥，也可以表达事件顺序和资源计数。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003013, 10003, 'JUDGE', 'HARD', 'LRU 页面置换算法属于栈算法，因此不会出现 Belady 异常。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', 'LRU 满足包含性质，增加页框不会提高缺页次数。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003014, 10003, 'JUDGE', 'EASY', '进程上下文切换完全没有时间和缓存方面的开销。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '上下文保存恢复、调度以及缓存和 TLB 影响都会产生开销。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003015, 10003, 'BLANK', 'MEDIUM', '分页系统中，将虚拟页号映射为物理页框号的核心数据结构是 ______。', NULL, '页表', '页表保存虚拟页到物理页框的映射及权限等状态。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003016, 10003, 'BLANK', 'HARD', '进程频繁发生缺页并将大部分时间用于页面换入换出的现象称为 ______。', NULL, '抖动', '工作集超过可用页框时可能出现抖动，也常称颠簸。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003017, 10003, 'SHORT', 'MEDIUM', '比较进程与线程在资源拥有和切换开销方面的差异。', NULL, '进程拥有独立地址空间和资源，隔离性强但切换开销较大；同一进程的线程共享多数资源，切换通常更轻量但需要同步保护共享状态。', '应同时说明地址空间、资源共享、隔离性和切换开销。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003018, 10003, 'SHORT', 'HARD', '说明死锁预防与死锁避免的区别。', NULL, '死锁预防通过破坏至少一个必要条件从机制上排除死锁；死锁避免在分配前检查系统是否仍处于安全状态并拒绝危险分配。', '预防是静态约束必要条件，避免是动态评估安全状态。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003019, 10003, 'SHORT', 'MEDIUM', '简述写时复制的基本思想及典型用途。', NULL, '多个执行单元先共享只读物理页，只有一方尝试写入时才复制对应页面；典型用于 fork 后延迟复制地址空间。', '应说明共享、写保护、写入触发复制及 fork 场景。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10003020, 10003, 'SHORT', 'MEDIUM', '虚拟内存给程序和操作系统带来哪些主要好处？', NULL, '虚拟内存提供统一且隔离的地址空间，允许程序按需装入、共享受控页面，并使程序可使用超过当前物理内存的逻辑空间。', '答案应覆盖抽象、隔离、按需分页以及受控共享等作用。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2)
ON DUPLICATE KEY UPDATE subject_id=VALUES(subject_id), type=VALUES(type), difficulty=VALUES(difficulty), content=VALUES(content), options_json=VALUES(options_json), answer=VALUES(answer), analysis=VALUES(analysis), default_score=VALUES(default_score), creator_id=VALUES(creator_id), update_time=CURRENT_TIMESTAMP(3), update_by=VALUES(update_by);

-- 数据库系统：5 单选、5 多选、4 判断、2 填空、4 简答。
INSERT INTO question(id, subject_id, type, difficulty, content, options_json, answer, analysis, default_score, creator_id, create_time, update_time, create_by, update_by) VALUES
  (10004001, 10004, 'SINGLE', 'EASY', '关系表中的主键应满足什么基本要求？', '[{"label":"A","value":"可以重复且可以为空"},{"label":"B","value":"唯一且不能为空"},{"label":"C","value":"必须由字符串组成"},{"label":"D","value":"只能包含一列"}]', 'B', '主键用于唯一标识一行，因此要求唯一且非空，也可以由多列组成。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004002, 10004, 'SINGLE', 'EASY', 'ACID 中用于描述并发事务相互隔离程度的是？', '[{"label":"A","value":"原子性"},{"label":"B","value":"一致性"},{"label":"C","value":"隔离性"},{"label":"D","value":"持久性"}]', 'C', '隔离性约束并发事务之间可见的中间状态。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004003, 10004, 'SINGLE', 'EASY', 'SQL 中用于对分组后的结果进行条件过滤的子句是？', '[{"label":"A","value":"WHERE"},{"label":"B","value":"HAVING"},{"label":"C","value":"ORDER BY"},{"label":"D","value":"LIMIT"}]', 'B', 'WHERE 在分组前过滤行，HAVING 在分组聚合后过滤组。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004004, 10004, 'SINGLE', 'MEDIUM', '消除非主属性对候选键的部分函数依赖，至少需要满足哪一范式？', '[{"label":"A","value":"第一范式"},{"label":"B","value":"第二范式"},{"label":"C","value":"第三范式"},{"label":"D","value":"第四范式"}]', 'B', '第二范式要求在第一范式基础上消除非主属性对候选键的部分依赖。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004005, 10004, 'SINGLE', 'MEDIUM', '主流关系数据库常用哪种树结构实现普通磁盘索引？', '[{"label":"A","value":"B+ 树"},{"label":"B","value":"二叉搜索树"},{"label":"C","value":"表达式树"},{"label":"D","value":"霍夫曼树"}]', 'A', 'B+ 树扇出高、层数低，并支持高效范围扫描。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004006, 10004, 'MULTI', 'EASY', '下列哪些属于常见的数据操纵语句？', '[{"label":"A","value":"INSERT"},{"label":"B","value":"UPDATE"},{"label":"C","value":"DELETE"},{"label":"D","value":"CREATE DATABASE"}]', 'A,B,C', 'INSERT、UPDATE、DELETE 操纵数据；CREATE DATABASE 属于数据定义。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004007, 10004, 'MULTI', 'EASY', 'SQL 标准中的连接类型包括哪些？', '[{"label":"A","value":"INNER JOIN"},{"label":"B","value":"LEFT JOIN"},{"label":"C","value":"RIGHT JOIN"},{"label":"D","value":"FULL OUTER JOIN"}]', 'A,B,C,D', '四项都是 SQL 定义的连接类型，但具体数据库可能不直接支持其中某些语法。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004008, 10004, 'MULTI', 'MEDIUM', '并发事务可能产生哪些典型现象？', '[{"label":"A","value":"脏读"},{"label":"B","value":"不可重复读"},{"label":"C","value":"幻读"},{"label":"D","value":"语法解析失败"}]', 'A,B,C', '前三项属于并发可见性现象；语法解析失败与并发事务无关。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004009, 10004, 'MULTI', 'MEDIUM', '事务的 ACID 特性包括哪些？', '[{"label":"A","value":"原子性"},{"label":"B","value":"一致性"},{"label":"C","value":"隔离性"},{"label":"D","value":"持久性"}]', 'A,B,C,D', 'ACID 分别是 Atomicity、Consistency、Isolation、Durability。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004010, 10004, 'MULTI', 'HARD', '下列哪些查询位置通常可能受益于合适的索引？', '[{"label":"A","value":"WHERE 过滤列"},{"label":"B","value":"JOIN 连接列"},{"label":"C","value":"ORDER BY 排序列"},{"label":"D","value":"SQL 注释文本"}]', 'A,B,C', '过滤、连接和排序都可能利用索引，注释不会参与查询执行。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004011, 10004, 'JUDGE', 'EASY', '事务成功提交后，其持久化修改在系统正常恢复后应当仍然存在。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', '这描述了事务的持久性。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004012, 10004, 'JUDGE', 'MEDIUM', '增加外键约束一定会提高写入性能。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '外键增强引用完整性，但检查和级联行为通常会增加写入成本。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004013, 10004, 'JUDGE', 'MEDIUM', '第三范式要求非主属性不应传递依赖于候选键。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', '第三范式旨在消除非主属性对候选键的传递依赖。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004014, 10004, 'JUDGE', 'HARD', '一张表上的索引越多，其所有读写操作就一定越快。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '索引可能加速特定读取，但会占用空间并增加写入维护成本。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004015, 10004, 'BLANK', 'EASY', 'SELECT 查询中用于消除结果重复行的关键字是 ______。', NULL, 'DISTINCT', 'DISTINCT 对选择列表的组合值进行去重。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004016, 10004, 'BLANK', 'MEDIUM', '乐观锁常通过在记录中增加并校验一个 ______ 字段来检测并发更新。', NULL, 'version', '更新时在条件中携带旧版本号并递增版本，可检测写冲突。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004017, 10004, 'SHORT', 'MEDIUM', '数据库规范化设计的主要目的是什么？', NULL, '通过分解关系减少数据冗余和更新异常，明确数据依赖，并在完整性与查询效率之间取得合理平衡。', '应说明冗余、插入删除更新异常以及依赖关系。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004018, 10004, 'SHORT', 'HARD', '简述 MVCC 如何支持并发读取。', NULL, 'MVCC 保存记录的多个版本并根据事务可见性规则选择可读版本，使读操作通常无需阻塞正在修改同一记录的写操作。', '应包含多版本、事务快照或可见性判断，以及降低读写冲突。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004019, 10004, 'SHORT', 'HARD', '设计联合索引时应考虑哪些因素？', NULL, '应考虑高频查询的过滤、连接和排序模式，列选择性、最左前缀、范围条件、覆盖索引收益以及额外写入和存储成本。', '答案应以真实查询模式为核心，而不是只按列选择性机械排序。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10004020, 10004, 'SHORT', 'MEDIUM', '发现一条 SQL 查询很慢时，可以按什么步骤初步诊断？', NULL, '先记录实际 SQL 和参数，再查看执行计划、扫描行数、索引使用、锁等待和数据分布，随后针对证据调整查询或索引并复测。', '重点是用执行计划和运行数据定位原因，修改后进行对比验证。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2)
ON DUPLICATE KEY UPDATE subject_id=VALUES(subject_id), type=VALUES(type), difficulty=VALUES(difficulty), content=VALUES(content), options_json=VALUES(options_json), answer=VALUES(answer), analysis=VALUES(analysis), default_score=VALUES(default_score), creator_id=VALUES(creator_id), update_time=CURRENT_TIMESTAMP(3), update_by=VALUES(update_by);

-- Java 程序设计：5 单选、5 多选、4 判断、2 填空、4 简答。
INSERT INTO question(id, subject_id, type, difficulty, content, options_json, answer, analysis, default_score, creator_id, create_time, update_time, create_by, update_by) VALUES
  (10005001, 10005, 'SINGLE', 'EASY', 'Java 源代码通常先被编译成什么形式再由 JVM 执行？', '[{"label":"A","value":"机器码文本"},{"label":"B","value":"字节码"},{"label":"C","value":"SQL"},{"label":"D","value":"汇编宏"}]', 'B', 'javac 通常生成 class 字节码，由 JVM 解释或即时编译执行。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005002, 10005, 'SINGLE', 'EASY', 'Java 中 String 对象最重要的特性之一是？', '[{"label":"A","value":"内容可原地修改"},{"label":"B","value":"不可变"},{"label":"C","value":"只能存储 ASCII"},{"label":"D","value":"不能比较"}]', 'B', 'String 不可变，修改字符串内容会产生新的字符串对象或结果。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005003, 10005, 'SINGLE', 'EASY', '需要按下标频繁随机访问元素时，通常优先选择哪个集合？', '[{"label":"A","value":"ArrayList"},{"label":"B","value":"LinkedList"},{"label":"C","value":"HashSet"},{"label":"D","value":"TreeSet"}]', 'A', 'ArrayList 基于连续数组，可在 O(1) 时间按下标访问。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005004, 10005, 'SINGLE', 'MEDIUM', '下列哪一种异常通常属于受检异常？', '[{"label":"A","value":"NullPointerException"},{"label":"B","value":"IllegalArgumentException"},{"label":"C","value":"IOException"},{"label":"D","value":"ArithmeticException"}]', 'C', 'IOException 继承 Exception 且不属于 RuntimeException，通常需要捕获或声明。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005005, 10005, 'SINGLE', 'MEDIUM', '若两个对象按照 equals 方法相等，关于 hashCode 的正确要求是？', '[{"label":"A","value":"二者 hashCode 必须相同"},{"label":"B","value":"二者 hashCode 必须不同"},{"label":"C","value":"hashCode 必须等于内存地址"},{"label":"D","value":"没有任何约束"}]', 'A', 'equals 相等的对象必须具有相同 hashCode，反向则不一定成立。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005006, 10005, 'MULTI', 'EASY', '面向对象程序设计的常见核心特征包括哪些？', '[{"label":"A","value":"封装"},{"label":"B","value":"继承"},{"label":"C","value":"多态"},{"label":"D","value":"抽象"}]', 'A,B,C,D', '封装、继承、多态和抽象都是常见的面向对象核心概念。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005007, 10005, 'MULTI', 'EASY', 'Java 的成员访问控制形式包括哪些？', '[{"label":"A","value":"public"},{"label":"B","value":"protected"},{"label":"C","value":"包级默认访问"},{"label":"D","value":"private"}]', 'A,B,C,D', 'Java 提供 public、protected、无修饰符的包级访问和 private。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005008, 10005, 'MULTI', 'MEDIUM', 'Java 集合框架中的主要接口包括哪些？', '[{"label":"A","value":"List"},{"label":"B","value":"Set"},{"label":"C","value":"Map"},{"label":"D","value":"Thread"}]', 'A,B,C', 'List、Set 和 Map 是集合框架核心接口，Thread 表示线程。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005009, 10005, 'MULTI', 'MEDIUM', '下列哪些接口属于函数式接口，可作为 Lambda 表达式的目标类型？', '[{"label":"A","value":"Runnable"},{"label":"B","value":"Comparator"},{"label":"C","value":"Callable"},{"label":"D","value":"Serializable"}]', 'A,B,C', 'Runnable、Comparator 和 Callable 各有一个抽象方法；Serializable 是标记接口。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005010, 10005, 'MULTI', 'HARD', '关于 try-with-resources，下列说法哪些正确？', '[{"label":"A","value":"资源通常需要实现 AutoCloseable"},{"label":"B","value":"资源会按声明的相反顺序关闭"},{"label":"C","value":"关闭异常可能作为受抑制异常保存"},{"label":"D","value":"只能管理文件资源"}]', 'A,B,C', '该语法适用于 AutoCloseable 资源，按逆序关闭并支持 suppressed exceptions，不限于文件。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005011, 10005, 'JUDGE', 'EASY', 'Java 类可以同时继承两个不同的父类。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', 'Java 类只支持单继承，但可以实现多个接口。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005012, 10005, 'JUDGE', 'MEDIUM', 'java.util.HashMap 本身保证多个线程并发修改时的线程安全。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', 'HashMap 不提供并发修改安全保证，可根据场景使用同步或 ConcurrentHashMap。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005013, 10005, 'JUDGE', 'EASY', 'StringBuilder 的字符内容可以在同一个对象上修改。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'A', 'StringBuilder 是可变字符序列，适合单线程内频繁拼接。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005014, 10005, 'JUDGE', 'HARD', '无论程序如何终止，finally 代码块都必然执行。', '[{"label":"A","value":"true"},{"label":"B","value":"false"}]', 'B', '例如调用 System.exit、进程崩溃或机器断电时，finally 可能无法执行。', 2, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005015, 10005, 'BLANK', 'EASY', 'Java 应用程序最常见的入口方法完整声明为 ______。', NULL, 'public static void main(String[] args)', 'JVM 通过 public static void main(String[] args) 作为常见应用入口。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005016, 10005, 'BLANK', 'MEDIUM', 'Java 中可用于声明内置监视器互斥方法或代码块的关键字是 ______。', NULL, 'synchronized', 'synchronized 基于对象监视器提供互斥与可见性保证。', 3, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005017, 10005, 'SHORT', 'MEDIUM', '说明 Java 中 == 与 equals 方法比较对象时的区别。', NULL, '对引用类型，== 比较两个引用是否指向同一对象；equals 可由类重写以比较业务意义上的内容是否相等。', '还可说明 Object 默认 equals 与 == 等价，以及重写 equals 时需配套重写 hashCode。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005018, 10005, 'SHORT', 'MEDIUM', '简述 Java 垃圾回收的目标以及它不能替代的资源管理工作。', NULL, '垃圾回收自动回收不可达对象占用的堆内存，但不能保证及时释放文件、网络连接、锁等外部资源，这些资源仍需显式关闭。', '应区分 JVM 堆内存管理与外部资源生命周期管理。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005019, 10005, 'SHORT', 'HARD', '比较 Java 接口与抽象类的典型使用场景。', NULL, '接口适合定义可由无关类型共同实现的能力契约并支持多实现；抽象类适合共享状态、构造逻辑和部分实现，表达更强的继承关系。', '答案应覆盖契约、多实现、共享状态和继承关系，而非只列语法差异。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2),
  (10005020, 10005, 'SHORT', 'HARD', '使用线程池执行任务相比每个任务创建一个新线程有哪些好处？', NULL, '线程池复用线程以降低创建销毁成本，限制并发度和资源占用，提供任务排队、拒绝策略、监控及统一生命周期管理。', '应说明复用、并发边界、队列和管理能力，同时认识到线程池参数仍需按负载设计。', 8, 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 2, 2)
ON DUPLICATE KEY UPDATE subject_id=VALUES(subject_id), type=VALUES(type), difficulty=VALUES(difficulty), content=VALUES(content), options_json=VALUES(options_json), answer=VALUES(answer), analysis=VALUES(analysis), default_score=VALUES(default_score), creator_id=VALUES(creator_id), update_time=CURRENT_TIMESTAMP(3), update_by=VALUES(update_by);

COMMIT;
