ALTER TABLE `grade_result`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '成绩结果主键',
    MODIFY COLUMN `runtime_submission_id` BIGINT NOT NULL COMMENT '运行时提交记录 ID',
    MODIFY COLUMN `objective_score` INT NOT NULL DEFAULT 0 COMMENT '客观题得分',
    MODIFY COLUMN `subjective_score` INT NOT NULL DEFAULT 0 COMMENT '主观题得分',
    MODIFY COLUMN `total_score` INT NOT NULL DEFAULT 0 COMMENT '总分',
    MODIFY COLUMN `pass_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否及格（1是，0否）',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '成绩状态',
    MODIFY COLUMN `completed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '阅卷完成时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `grading_answer_result`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '阅卷答案结果主键',
    MODIFY COLUMN `runtime_submission_id` BIGINT NOT NULL COMMENT '运行时提交记录 ID',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '题目 ID',
    MODIFY COLUMN `question_content` TEXT NULL COMMENT '题目内容快照',
    MODIFY COLUMN `objective_flag` TINYINT NOT NULL COMMENT '是否客观题（1是，0否）',
    MODIFY COLUMN `correct_flag` TINYINT NULL DEFAULT NULL COMMENT '是否答对（1是，0否）',
    MODIFY COLUMN `earned_score` INT NOT NULL DEFAULT 0 COMMENT '本题得分',
    MODIFY COLUMN `max_score` INT NOT NULL COMMENT '本题满分',
    MODIFY COLUMN `create_time` DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NOT NULL COMMENT '更新时间';

ALTER TABLE `grading_submission`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '阅卷提交主键',
    MODIFY COLUMN `runtime_submission_id` BIGINT NOT NULL COMMENT '运行时提交记录 ID',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `exam_name` VARCHAR(128) NULL DEFAULT NULL COMMENT '考试名称快照',
    MODIFY COLUMN `pass_score` INT NOT NULL DEFAULT 0 COMMENT '及格分数',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `paper_snapshot_id` BIGINT NOT NULL COMMENT '试卷快照 ID',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '阅卷状态',
    MODIFY COLUMN `submitted_at` DATETIME(3) NOT NULL COMMENT '交卷时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `grading_task`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '主观题阅卷任务主键',
    MODIFY COLUMN `grading_submission_id` BIGINT NOT NULL COMMENT '阅卷提交 ID',
    MODIFY COLUMN `exam_id` BIGINT NOT NULL COMMENT '考试 ID',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `exam_name` VARCHAR(128) NULL DEFAULT NULL COMMENT '考试名称快照',
    MODIFY COLUMN `question_id` BIGINT NOT NULL COMMENT '题目 ID',
    MODIFY COLUMN `question_content` TEXT NULL COMMENT '题目内容快照',
    MODIFY COLUMN `reference_answer` TEXT NULL COMMENT '参考答案',
    MODIFY COLUMN `analysis` TEXT NULL COMMENT '题目解析',
    MODIFY COLUMN `answer_text` TEXT NULL COMMENT '学生作答内容',
    MODIFY COLUMN `submitted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '交卷时间',
    MODIFY COLUMN `sort_order` INT NULL DEFAULT NULL COMMENT '题目排序号',
    MODIFY COLUMN `answer_id` BIGINT NOT NULL COMMENT '答案记录 ID',
    MODIFY COLUMN `max_score` INT NOT NULL COMMENT '本题满分',
    MODIFY COLUMN `status` VARCHAR(32) NOT NULL COMMENT '任务状态',
    MODIFY COLUMN `assigned_teacher_id` BIGINT NULL DEFAULT NULL COMMENT '分配教师 ID',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间';

ALTER TABLE `inbox_event`
    MODIFY COLUMN `event_id` VARCHAR(36) NOT NULL COMMENT '消息事件标识',
    MODIFY COLUMN `consumer_name` VARCHAR(64) NOT NULL COMMENT '消费者名称',
    MODIFY COLUMN `processed_at` DATETIME(3) NOT NULL COMMENT '消息处理完成时间';

ALTER TABLE `outbox_event`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN `event_type` VARCHAR(128) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN `payload_json` JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '发布状态',
    MODIFY COLUMN `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN `next_retry_time` DATETIME(3) NULL DEFAULT NULL COMMENT '下次重试时间',
    MODIFY COLUMN `lease_token` VARCHAR(36) NULL DEFAULT NULL COMMENT '发布租约令牌',
    MODIFY COLUMN `lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN `last_error` VARCHAR(1000) NULL DEFAULT NULL COMMENT '最近一次发布失败原因',
    MODIFY COLUMN `failed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '最终发布失败时间',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '事件创建时间',
    MODIFY COLUMN `published_at` DATETIME(3) NULL DEFAULT NULL COMMENT '发布成功时间';

ALTER TABLE `subjective_grade`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '主观题评分记录主键',
    MODIFY COLUMN `grading_task_id` BIGINT NOT NULL COMMENT '阅卷任务 ID',
    MODIFY COLUMN `teacher_id` BIGINT NOT NULL COMMENT '评分教师 ID',
    MODIFY COLUMN `score` INT NOT NULL COMMENT '评分',
    MODIFY COLUMN `comment` VARCHAR(255) NULL DEFAULT NULL COMMENT '评分评语',
    MODIFY COLUMN `graded_at` DATETIME(3) NOT NULL COMMENT '评分时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间';
