package com.ekusys.exam.runtime.service;

import com.baomidou.mybatisplus.core.toolkit.IdWorker;
import com.ekusys.exam.common.exception.BusinessException;
import com.ekusys.exam.common.security.SecurityUtils;
import com.ekusys.exam.content.api.PaperSnapshotQuestion;
import com.ekusys.exam.exam.dto.*;
import com.ekusys.exam.management.api.RuntimeExamSnapshot;
import com.ekusys.exam.runtime.client.ManagementRuntimeClient;
import com.ekusys.exam.runtime.messaging.RuntimeOutboxService;
import com.ekusys.exam.runtime.api.GradingAnswerInput;
import com.ekusys.exam.runtime.api.GradingSubmissionInput;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.LocalDateTime;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ExamRuntimeService {
 private final JdbcTemplate jdbc; private final ManagementRuntimeClient management; private final ObjectMapper mapper;private final RuntimeOutboxService outbox;private final TimeoutSubmissionService timeoutSubmissionService;
 public ExamRuntimeService(JdbcTemplate jdbc,ManagementRuntimeClient management,ObjectMapper mapper,RuntimeOutboxService outbox,TimeoutSubmissionService timeoutSubmissionService){this.jdbc=jdbc;this.management=management;this.mapper=mapper;this.outbox=outbox;this.timeoutSubmissionService=timeoutSubmissionService;}
 public List<StudentExamView> listStudent(){Long uid=requireUser();return management.student(uid).getData().stream().map(s->StudentExamView.builder().examId(s.examId()).name(s.name()).startTime(s.startTime()).endTime(s.endTime()).durationMinutes(s.durationMinutes()).status(s.status()).submitted(submitted(s.examId(),uid)).proctoringLevel(s.proctoringLevel()).proctoringPolicy(policy(s)).build()).toList();}
 @Transactional public StartExamResponse start(Long examId){Long uid=requireUser();RuntimeExamSnapshot s=management.snapshot(examId).getData();LocalDateTime now=dbNow();if(!s.candidateIds().contains(uid))throw new BusinessException("你不在本场考试名单中");if(now.isBefore(s.startTime())||now.isAfter(s.endTime()))throw new BusinessException("当前不在考试时间内");
  List<SessionRow> rows=jdbc.query("select id,start_time,deadline_time,status from exam_session where exam_id=? and student_id=?",(rs,n)->new SessionRow(rs.getLong("id"),rs.getObject("start_time",LocalDateTime.class),rs.getObject("deadline_time",LocalDateTime.class),rs.getString("status")),examId,uid);boolean resumed=!rows.isEmpty();SessionRow row;
  if(resumed){row=rows.getFirst();if(!"ANSWERING".equals(row.status()))throw new BusinessException("你已提交过本场考试");}
  else{LocalDateTime deadline=now.plusMinutes(s.durationMinutes()).isBefore(s.endTime())?now.plusMinutes(s.durationMinutes()):s.endTime();long id=IdWorker.getId();jdbc.update("insert into exam_session(id,exam_id,student_id,status,start_time,deadline_time,create_time,update_time) values(?,?,?,'ANSWERING',?,?,current_timestamp(3),current_timestamp(3))",id,examId,uid,now,deadline);jdbc.update("insert into submission(id,exam_id,student_id,status,paper_snapshot_id,timeout_submit,create_time,update_time) values(?,?,?,'IN_PROGRESS',?,0,current_timestamp(3),current_timestamp(3))",IdWorker.getId(),examId,uid,s.paper().snapshotId());outbox.sessionStarted(examId,uid);row=new SessionRow(id,now,deadline,"ANSWERING");}
  List<StudentExamQuestionView> questions=s.paper().questions().stream().map(q->question(q,currentAnswer(examId,uid,q.questionId()))).toList();return StartExamResponse.builder().examId(examId).examName(s.name()).resumed(resumed).durationMinutes(s.durationMinutes()).startTime(row.start()).endTime(s.endTime()).deadlineTime(row.deadline()).proctoringPolicy(policy(s)).questions(questions).build();}
 @Transactional public SnapshotAckView snapshot(Long examId,SnapshotRequest request){Long uid=requireUser();SessionRow row=active(examId,uid);if(!dbNow().isBefore(row.deadline()))throw new BusinessException("考试作答时间已结束");saveAnswers(examId,uid,request.getAnswers(),"SNAPSHOT",false);LocalDateTime now=dbNow();jdbc.update("update exam_session set last_snapshot_time=?,update_time=? where id=?",now,now,row.id());return SnapshotAckView.builder().serverReceivedAt(now).clientTimestamp(request.getClientTimestamp()).snapshotVersion(request.getSnapshotVersion()).build();}
 @Transactional public SubmitResultView submit(Long examId,SubmitExamRequest request){Long uid=requireUser();SessionRow row=active(examId,uid);boolean expired=!dbNow().isBefore(row.deadline());Long sid=submissionId(examId,uid);if(expired){timeoutSubmissionService.submitExpired(row.id(),examId,uid);return SubmitResultView.builder().submissionId(sid).status("PROCESSING").build();}saveAnswers(examId,uid,request.getAnswers(),"SUBMIT",true);jdbc.update("update submission set status='PROCESSING',submitted_at=current_timestamp(3),timeout_submit=0,update_time=current_timestamp(3) where id=?",sid);jdbc.update("update exam_session set status='SUBMITTED',end_time=current_timestamp(3),update_time=current_timestamp(3) where id=?",row.id());outbox.submissionAccepted(sid);return SubmitResultView.builder().submissionId(sid).status("PROCESSING").build();}
 @Transactional public void antiCheat(Long examId,AntiCheatEventRequest r){Long uid=requireUser();active(examId,uid);long eventId=IdWorker.getId();jdbc.update("insert into anti_cheat_event(id,exam_id,student_id,event_type,event_time,duration_ms,payload,evidence_json,create_time,update_time) values(?,?,?,?,current_timestamp(3),?,?,?,current_timestamp(3),current_timestamp(3))",eventId,examId,uid,r.getEventType(),r.getDurationMs(),r.getPayload(),r.getEvidenceJson());outbox.proctoringEvent(eventId);}
 public GradingSubmissionInput gradingInput(Long submissionId){List<GradingSubmissionInput> rows=jdbc.query("select id,exam_id,student_id,paper_snapshot_id,submitted_at from submission where id=?",(rs,n)->new GradingSubmissionInput(rs.getLong("id"),rs.getLong("exam_id"),rs.getLong("student_id"),null,null,rs.getLong("paper_snapshot_id"),rs.getObject("submitted_at",LocalDateTime.class),List.of()),submissionId);if(rows.isEmpty())throw new BusinessException("交卷记录不存在");GradingSubmissionInput row=rows.getFirst();RuntimeExamSnapshot exam=management.snapshot(row.examId()).getData();List<GradingAnswerInput> answers=jdbc.query("select id,question_id,answer_text from submission_answer where submission_id=?",(rs,n)->new GradingAnswerInput(rs.getLong("id"),rs.getLong("question_id"),rs.getString("answer_text")),submissionId);return new GradingSubmissionInput(row.submissionId(),row.examId(),row.studentId(),exam.name(),exam.passScore(),row.paperSnapshotId(),row.submittedAt(),answers);}
 private void saveAnswers(Long examId,Long uid,List<AnswerPayload> answers,String source,boolean finalAnswer){Long sid=submissionId(examId,uid);for(AnswerPayload a:answers){jdbc.update("delete from submission_answer where submission_id=? and question_id=?",sid,a.getQuestionId());jdbc.update("insert into submission_answer(id,submission_id,question_id,answer_text,final_answer,source,create_time,update_time) values(?,?,?,?,?,?,current_timestamp(3),current_timestamp(3))",IdWorker.getId(),sid,a.getQuestionId(),a.getAnswerText(),finalAnswer?1:0,source);}}
 private SessionRow active(Long examId,Long uid){List<SessionRow> r=jdbc.query("select id,start_time,deadline_time,status from exam_session where exam_id=? and student_id=?",(rs,n)->new SessionRow(rs.getLong("id"),rs.getObject("start_time",LocalDateTime.class),rs.getObject("deadline_time",LocalDateTime.class),rs.getString("status")),examId,uid);if(r.isEmpty()||!"ANSWERING".equals(r.getFirst().status()))throw new BusinessException("会话已结束");return r.getFirst();}
 private Long submissionId(Long examId,Long uid){return jdbc.queryForObject("select id from submission where exam_id=? and student_id=?",Long.class,examId,uid);}
 private String currentAnswer(Long examId,Long uid,Long qid){List<String> v=jdbc.queryForList("select a.answer_text from submission_answer a join submission s on s.id=a.submission_id where s.exam_id=? and s.student_id=? and a.question_id=? limit 1",String.class,examId,uid,qid);return v.isEmpty()?null:v.getFirst();}
 private boolean submitted(Long examId,Long uid){Integer c=jdbc.queryForObject("select count(*) from submission where exam_id=? and student_id=? and status<>'IN_PROGRESS'",Integer.class,examId,uid);return c!=null&&c>0;}
 private StudentExamQuestionView question(PaperSnapshotQuestion q,String answer){return StudentExamQuestionView.builder().questionId(q.questionId()).type(q.type()).content(q.content()).optionsJson(q.optionsJson()).score(q.score()).sortOrder(q.sortOrder()).currentAnswer(answer).assets(q.assets().stream().map(a->com.ekusys.exam.question.dto.QuestionImageUploadView.builder().assetId(a.assetId()).url(a.url()).objectKey(a.objectKey()).originalName(a.originalName()).size(a.size()).fileType(a.fileType()).build()).toList()).build();}
 private ProctoringPolicyView policy(RuntimeExamSnapshot s){try{return s.proctoringConfigJson()==null?ProctoringPolicyView.builder().level(s.proctoringLevel()).build():mapper.readValue(s.proctoringConfigJson(),ProctoringPolicyView.class);}catch(Exception e){return ProctoringPolicyView.builder().level(s.proctoringLevel()).build();}}
 private LocalDateTime dbNow(){return jdbc.queryForObject("select current_timestamp(3)",LocalDateTime.class);} private Long requireUser(){Long id=SecurityUtils.getCurrentUserId();if(id==null)throw new BusinessException("未登录");return id;} private record SessionRow(Long id,LocalDateTime start,LocalDateTime deadline,String status){}
}
