ALTER TABLE `outbox_event`
    MODIFY COLUMN `id` VARCHAR(36) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN `aggregate_type` VARCHAR(64) NOT NULL COMMENT '聚合根类型',
    MODIFY COLUMN `aggregate_id` VARCHAR(64) NOT NULL COMMENT '聚合根标识',
    MODIFY COLUMN `event_type` VARCHAR(128) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN `payload_json` JSON NOT NULL COMMENT '事件载荷 JSON',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '发布状态',
    MODIFY COLUMN `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN `next_retry_time` DATETIME(3) NULL DEFAULT NULL COMMENT '下次重试时间',
    MODIFY COLUMN `lease_token` VARCHAR(36) NULL DEFAULT NULL COMMENT '发布租约令牌',
    MODIFY COLUMN `lease_until` DATETIME(3) NULL DEFAULT NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN `last_error` VARCHAR(1000) NULL DEFAULT NULL COMMENT '最近一次发布失败原因',
    MODIFY COLUMN `failed_at` DATETIME(3) NULL DEFAULT NULL COMMENT '最终发布失败时间',
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL COMMENT '事件创建时间',
    MODIFY COLUMN `published_at` DATETIME(3) NULL DEFAULT NULL COMMENT '发布成功时间';

ALTER TABLE `student_profile`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '学生档案主键',
    MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '关联用户 ID',
    MODIFY COLUMN `student_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '学号',
    MODIFY COLUMN `enrollment_year` VARCHAR(16) NULL DEFAULT NULL COMMENT '入学年份',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '学籍状态',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `student_teaching_class`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '学生教学班关联主键',
    MODIFY COLUMN `student_id` BIGINT NOT NULL COMMENT '学生 ID',
    MODIFY COLUMN `subject_id` BIGINT NOT NULL COMMENT '学科 ID',
    MODIFY COLUMN `teaching_class_id` BIGINT NOT NULL COMMENT '教学班 ID',
    MODIFY COLUMN `enroll_status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '选课状态',
    MODIFY COLUMN `enrolled_at` DATETIME(3) NULL DEFAULT NULL COMMENT '加入教学班时间',
    MODIFY COLUMN `dropped_at` DATETIME(3) NULL DEFAULT NULL COMMENT '退课时间',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `subject`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '学科主键',
    MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '学科名称',
    MODIFY COLUMN `description` VARCHAR(255) NULL DEFAULT NULL COMMENT '学科简介',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `teacher_profile`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '教师档案主键',
    MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '关联用户 ID',
    MODIFY COLUMN `teacher_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '工号',
    MODIFY COLUMN `title` VARCHAR(32) NULL DEFAULT NULL COMMENT '职称',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '教师状态',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';

ALTER TABLE `teaching_class`
    MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '教学班主键',
    MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '教学班名称',
    MODIFY COLUMN `subject_id` BIGINT NOT NULL COMMENT '学科 ID',
    MODIFY COLUMN `teacher_id` BIGINT NOT NULL COMMENT '任课教师 ID',
    MODIFY COLUMN `term` VARCHAR(32) NOT NULL COMMENT '学期标识',
    MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'ONGOING' COMMENT '教学班状态',
    MODIFY COLUMN `capacity` INT NULL DEFAULT NULL COMMENT '班级容量',
    MODIFY COLUMN `roster_version` BIGINT NOT NULL DEFAULT 0 COMMENT '花名册版本号',
    MODIFY COLUMN `create_time` DATETIME(3) NULL DEFAULT NULL COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME(3) NULL DEFAULT NULL COMMENT '更新时间',
    MODIFY COLUMN `create_by` BIGINT NULL DEFAULT NULL COMMENT '创建人 ID',
    MODIFY COLUMN `update_by` BIGINT NULL DEFAULT NULL COMMENT '更新人 ID';
